### ISSUE TITLE
Add missing bold fonts

### ISSUE THREAD

**Issue by openjck** [mozilla/ensemble#172]
I think we are using some varieties of the Fira Sans font that we are not hosting. When I installed all varieties of the Fira Sans font on my local machine, some content (section titles, chart titles, the site title) suddenly appeared more bold.

**Comment by spasovski** [comment]
yea i mean we load a crazy amount of js libs in modern SPAs that downloading a few fonts only when they are used isn't too bad

the fireplace project had like every variation since it was a packaged app and all the static assets would be installed at app download
