### ISSUE TITLE
Don't ignore repo URLs when testing links

### ISSUE THREAD

**Issue by openjck** [mozilla/ensemble#185]
The ensemble and ensemble-transposer repos are currently private, so we don't test those URLs when checking for broken links. Once the site launches and both repos are made public, we should stop ignoring them.

We currently ignore them here:

https://github.com/mozilla/ensemble/blob/19d2c9648d45b2a37bdc96af4e52a69979b5b606/src/tests/nightwatch/utils.js#L37-L43

**Comment by openjck** [comment]
Done with 89d63fdc98d1afbda80946faa40ac32b426745b2. Not sure why GitHub hasn't been auto-closing issues lately.

**Comment by pdehaan** [comment]
> Not sure why GitHub hasn't been auto-closing issues lately.

Did GitHub always close issues when committing directly to **master** branch, or does it only auto-close issues if they're in a merged PR?

**Comment by openjck** [comment]
According to [their docs](https://help.github.com/articles/closing-issues-using-keywords/), commits should count. I contacted them about it.
