### ISSUE TITLE
Remove chart concerning Unity NPAPI plugin

### ISSUE THREAD

**Issue by Eric-01** [mozilla/ensemble#328]
As the title says, remove chart concerning Unity NPAPI plugin, since these data are from 2016. Additionally, Firefox in (regular) version 52.0 dropped support for NPAPI plugins other than Flash Player, so showing this data these days is redundant.

**Comment by openjck** [comment]
Hi Eric. Thanks for the report. Just to confirm, do you mean removing this entire chart?

<img width="1224" alt="" src="https://user-images.githubusercontent.com/933396/60374311-cdb64580-99d1-11e9-8467-e821a3759828.png">

@fbertsch @SuYoungHong: What do you think about this? If we do remove it, would you like to remove it from your end? I can remove the data via ensemble-transposer, but there's no sense in sending it over if we don't want it and it's easy to stop generating.

**Comment by Eric-01** [comment]
First, I would like to apologize for the fact that you had to wait so long for my answer. And answering the question: yes, I had in mind removal of exactly this chart.

**Comment by openjck** [comment]
Thanks for the report, Eric. This has been fixed and will be deployed soon.
