### ISSUE TITLE
Add "data deleted" annotation to Daily Usage and Has Add-on charts

### ISSUE THREAD

**Issue by openjck** [mozilla/ensemble#337]
@SuYoungHong, can you please add the *data deleted (addons outage)* annotation to the *Daily Usage* and *Has Add-on* charts in addition to the YAU and MAU charts?

**Comment by SuYoungHong** [comment]
hey, thanks for your patience, I dropped the ball on this. I've got a PR submitted to the ETL repo here: 

https://github.com/mozilla/Fx_Usage_Report/pull/79

**Comment by openjck** [comment]
Fixed in the ETL repo.
