### ISSUE TITLE
onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ensemble#67]
Tried adding **eslint** to this repo, along w/ the **eslint-plugin-react** and **eslint-plugin-jsx-a11y** plugins, and got a few almost interesting results:

```
/Users/pdehaan/dev/github/mozilla/ensemble/src/components/views/CustomizableDateMetric.js
  14:13  warning  onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/no-onchange

/Users/pdehaan/dev/github/mozilla/ensemble/src/components/views/Dashboard.js
  19:17  warning  onBlur must be used instead of onchange, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users  jsx-a11y/no-onchange
```

https://github.com/mozilla/ensemble/blob/df6321788d83aa913a062340c1a01d1b8a6b0151/src/components/views/CustomizableDateMetric.js#L14

https://github.com/mozilla/ensemble/blob/df6321788d83aa913a062340c1a01d1b8a6b0151/src/components/views/Dashboard.js#L19

**Comment by arhoy** [comment]
> I went ahead and fixed the eslint errors.
> 
> Question about `onBlur`. When it's used with select boxes, it's only triggered after the select box loses focus. So in Ensemble, if someone uses a mouse to click on a country, they need to then click on another part of the page before the effect is seen. That's pretty weird. I'm thinking about continuing to use `onChange` because of that. Any thoughts?

My thoughts exactly. User Experience >> ESLint Error Lol

**Comment by yewyewXD** [comment]
this problem still exists in   "gatsby": "^2.25.2"
